sudo: false
language: c
dist: trusty
os: osx
before_install:
  - brew update
  - brew install valgrind
script:
  - unset TRAVIS_COMMIT_MESSAGE
  - git clone https://github.com/uael/42ShellTester.git st
  - make
  - make test
  - bash st/42ShellTester.sh --all --reference bash $PWD/42sh
