sudo: false
language: c
dist: trusty
os: osx
script:
  - unset TRAVIS_COMMIT_MESSAGE
  - git clone https://github.com/uael/42ShellTester.git st
  - make san
  - make testsan
  - bash st/42ShellTester.sh --reference bash $PWD/42sh.san
