sudo: false
language: c
dist: trusty

script:
  - make testsan
  - make valgrind

matrix:
  include:
    # default
    - os: linux
    - os: osx

    # osx
    - os: osx
      osx_image: xcode7.3
      compiler: clang
    - os: osx
      osx_image: xcode8.3
      compiler: clang

    # gcc
    - os: linux
      compiler: gcc

    # clang
    - os: linux
      compiler: clang
